language: php

php:
  - 5.6

before_script:
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:~1.0.0"
  - composer install

cache:
  directories:
    - vendor
    - /home/travis/.composer

script:
  - phpunit tests
